### ISSUE TITLE
调用 cli stat exec_balance 导致chain停掉了。windows solo模式, version="1.64.0-68f55015"

### ISSUE THREAD

**Issue by spoonerAhua** [33cn/chain33#969]
![image](https://user-images.githubusercontent.com/6853508/101566643-482e2600-3a0a-11eb-9883-4fc01d974191.png)

**Comment by spoonerAhua** [comment]
命令:cli stat exec_balance -a 1JT6Nu7zUg9oPbafHZFtKcL8VjL6ft92mC

**Comment by bysomeone** [comment]
单纯这个panic是配置问题，修改或添加配置项enableMVCCIter=true

```toml
[store.sub.kvmuccmavl]
enableMVCCIter=true
```
